### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by wasiahmad** [microsoft/PyCodeGPT#9]
Have you released the training data that is used to train APIRetriever?

**Comment by zdaoguang** [comment]
Sorry, we currently have no plans to release the training corpus for apiretriever due to company policy. However, we recommend that you can extract such the corpus on your own code corpus based on [our publicly available scripts](https://github.com/microsoft/PyCodeGPT/blob/main/apicoder/APIRetriever/scripts/run_extract_apiretriever_corpus.sh).

Thanks for your attention to our work.
